# Generated by Django 4.1.3 on 2022-11-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("H", "HARD"), ("S", "SOFT")], max_length=4
            ),
        ),
    ]
